In [1]:
import torch
import torch.nn as nn

/home/aiteam/miniconda3/envs/loader/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
i = torch.arange(25).reshape(5, 5).unsqueeze(0)
i.shape

torch.Size([1, 5, 5])

In [9]:
m = nn.AvgPool2d(5)
i = torch.arange(25, dtype=torch.float32).reshape(5, 5).unsqueeze(0)
m(i)

tensor([[[12.]]])

In [10]:
i

tensor([[[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.],
         [20., 21., 22., 23., 24.]]])

In [11]:
sum(torch.arange(25))/25

tensor(12.)

In [13]:
m = nn.AdaptiveAvgPool2d()
m(i)

tensor([[[12.]]])

In [14]:
class MyAdaptiveMaxPool2d(nn.Module):
    def __init__(self, sz=None):
        super().__init__()
    def forward(self, x): 
        inp_size = x.size()
        return nn.functional.max_pool2d(input=x,
                  kernel_size= (inp_size[2], inp_size[3]))

In [21]:
torch.squeeze(x).shape

torch.Size([32, 16, 256, 256])

In [24]:
x = torch.randn((32, 16, 256, 256))

gap = MyAdaptiveMaxPool2d()
gap(x).squeeze()

torch.Size([32, 16])

In [ ]:
"""
x [batch, channel_dim, width, height]
z [batch, latent_dim]
"""
class MyAdaptiveMaxPool2d(nn.Module):
    def __init__(self, sz=None):
        super().__init__()
    def forward(self, x): 
        inp_size = x.size()
        return nn.functional.max_pool2d(input=x,
                  kernel_size= (inp_size[2], inp_size[3]))
        
class GConv(nn.Module):
  def __init__(self, in_channels, out_channels, k_size):
    self.gap = MyAdaptiveMaxPool2d()
    self.linear = nn.Linear()
    self.conv2d = nn.Conv2d(in_channels, out_channels, kernel_size=k_size)
  def forwrad(self, x, z):
    x_m = self.gap(x)
    s = torch.sigmoid(self.linear(torch.concat((x_m, z), dim=0)))
    x = self.conv2d(x)
    